# Generated by Django 4.1.7 on 2023-02-20 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentNumber', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(7, 'Name must have atleast 3 charactors')])),
                ('Firstname', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Name must have atleast 3 charactors')])),
                ('MiddleName', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Name must have atleast 3 charactors')])),
                ('LastName', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Name must have atleast 3 charactors')])),
                ('photo', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
