# Generated by Django 4.1.7 on 2023-02-21 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ump_biometrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentNumber',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11, 'Name must have atleast 3 charactors')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
